### ISSUE TITLE
Make a release and register in General

### ISSUE THREAD

**Issue by ViralBShah** [xKDR/Lowess.jl#5]
I suggest reviewing the open PRs and making a release and registering in General if the package is ready. There will be a similarity issue with the name, but just open a registration PR with the current name and we'll discuss it in there to figure out if Lowess.jl is acceptable or brainstorm a new name.

**Comment by codetalker7** [comment]
> I suggest reviewing the open PRs and making a release and registering in General if the package is ready. There will be a similarity issue with the name, but just open a registration PR with the current name and we'll discuss it in there to figure out if Lowess.jl is acceptable or brainstorm a new name.

Hi Viral. Sure, it'll be done.

**Comment by codetalker7** [comment]
PR initiated: https://github.com/JuliaRegistries/General/pull/63100

**Comment by ayushpatnaikgit** [comment]
It is registered.
